# Generated by Django 4.2.6 on 2023-11-17 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_gear_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gear',
            options={'ordering': ['category', 'pk']},
        ),
        migrations.AlterField(
            model_name='cost',
            name='mythos_1',
            field=models.PositiveSmallIntegerField(db_comment='Number of Mythos I tokens needed to exchange for a piece of gear', default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cost',
            name='mythos_2',
            field=models.PositiveSmallIntegerField(db_comment='Number of Mythos II tokens needed to exchange for a piece of gear', default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cost',
            name='mythos_3',
            field=models.PositiveSmallIntegerField(db_comment='Number of Mythos III tokens needed to exchange for a piece of gear', default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cost',
            name='mythos_4',
            field=models.PositiveSmallIntegerField(db_comment='Number of Mythos IV tokens needed to exchange for a piece of gear', default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cost',
            name='tomestones',
            field=models.PositiveSmallIntegerField(db_comment='Number of Tomestones needed to exchange for a piece of gear', default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cost',
            name='unsung_acc',
            field=models.PositiveSmallIntegerField(db_comment='Number of Unsung Accessory tokens needed to exchange for a piece of gear', default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cost',
            name='unsung_body',
            field=models.PositiveSmallIntegerField(db_comment='Number of Unsung Body tokens needed to exchange for a piece of gear', default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cost',
            name='unsung_feet',
            field=models.PositiveSmallIntegerField(db_comment='Number of Unsung Feet tokens needed to exchange for a piece of gear', default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cost',
            name='unsung_hands',
            field=models.PositiveSmallIntegerField(db_comment='Number of Unsung Hands tokens needed to exchange for a piece of gear', default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cost',
            name='unsung_head',
            field=models.PositiveSmallIntegerField(db_comment='Number of Unsung Head tokens needed to exchange for a piece of gear', default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cost',
            name='unsung_legs',
            field=models.PositiveSmallIntegerField(db_comment='Number of Unsung Legs tokens needed to exchange for a piece of gear', default=0, null=True),
        ),
        migrations.AlterField(
            model_name='gearset',
            name='body',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gearset_body', to='api.gear'),
        ),
        migrations.AlterField(
            model_name='gearset',
            name='bracelet',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gearset_bracelet', to='api.gear'),
        ),
        migrations.AlterField(
            model_name='gearset',
            name='earring',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gearset_earring', to='api.gear'),
        ),
        migrations.AlterField(
            model_name='gearset',
            name='feet',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gearset_feet', to='api.gear'),
        ),
        migrations.AlterField(
            model_name='gearset',
            name='hands',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gearset_hands', to='api.gear'),
        ),
        migrations.AlterField(
            model_name='gearset',
            name='head',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gearset_head', to='api.gear'),
        ),
        migrations.AlterField(
            model_name='gearset',
            name='left_ring',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gearset_left_ring', to='api.gear'),
        ),
        migrations.AlterField(
            model_name='gearset',
            name='legs',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gearset_legs', to='api.gear'),
        ),
        migrations.AlterField(
            model_name='gearset',
            name='necklace',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gearset_necklace', to='api.gear'),
        ),
        migrations.AlterField(
            model_name='gearset',
            name='right_ring',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gearset_right_ring', to='api.gear'),
        ),
        migrations.AlterField(
            model_name='gearset',
            name='shield',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gearset_shield', to='api.gear'),
        ),
        migrations.AlterField(
            model_name='gearset',
            name='weapon',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gearset_weapon', to='api.gear'),
        ),
    ]
