# Generated by Django 4.2.6 on 2023-11-17 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_gear_options_alter_cost_mythos_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gear',
            name='ff14_db_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
