# Generated by Django 4.2.6 on 2023-11-17 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_gear_ff14_db_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='role',
            field=models.CharField(choices=[('tank', 'tank'), ('healer', 'healer'), ('melee', 'melee'), ('ranged', 'ranged'), ('caster', 'caster')], default=('tank', 'tank')),
            preserve_default=False,
        ),
    ]
