# Generated by Django 4.2.6 on 2023-11-17 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_job_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gear',
            name='ff14_db_url',
        ),
        migrations.AddField(
            model_name='gear',
            name='ff14_db_index',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
