# Generated by Django 4.2.6 on 2023-11-20 18:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_gear_ff14_db_url_gear_ff14_db_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gear',
            name='ff14_db_index',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='gear',
            name='name',
            field=models.CharField(db_comment='Name of the gear', unique=True),
        ),
        migrations.AlterField(
            model_name='gearset',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='gearset',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='name',
            field=models.CharField(db_comment='Name of the job', unique=True),
        ),
        migrations.AlterField(
            model_name='race',
            name='name',
            field=models.CharField(db_comment='Race name', unique=True),
        ),
    ]
