# Generated by Django 4.2.6 on 2023-11-20 18:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_gear_ff14_db_index_alter_gear_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cost',
            name='name',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='gear',
            name='acquisition',
            field=models.CharField(choices=[('NR', 'Normal Raid'), ('AR', 'Alliance Raid'), ('SR', 'Savage Raid'), ('TG', 'Tomestone Gear'), ('ATG', 'Augmented Tomestone Gear'), ('ETG', 'Exquisite Tomestone Weapon'), ('C_Normal_Q', 'Crafted Normal Quality'), ('C_High_Q', 'Crafted High Quality'), ('DD', 'Dungeon Drop'), ('RW', 'Relic Weapon')], db_comment='Way to obtain the gear', max_length=50),
        ),
        migrations.AlterField(
            model_name='gear',
            name='added_in_patch',
            field=models.CharField(choices=[('x.0', 'x.0'), ('x.1', 'x.1'), ('x.2', 'x.2'), ('x.3', 'x.3'), ('x.4', 'x.4'), ('x.5', 'x.5')], db_comment='Patch the gear was added on', max_length=50),
        ),
        migrations.AlterField(
            model_name='gear',
            name='category',
            field=models.CharField(choices=[('Fending', 'Fending'), ('Healing', 'Healing'), ('Striking', 'Striking'), ('Maiming', 'Maiming'), ('Scouting', 'Scouting'), ('Aiming', 'Aiming'), ('Casting', 'Casting'), ('Slaying', 'Slaying')], db_comment='Category of the gear', max_length=50),
        ),
        migrations.AlterField(
            model_name='gear',
            name='cost',
            field=models.OneToOneField(db_comment='Costs of the gear', max_length=50, on_delete=django.db.models.deletion.CASCADE, to='api.cost'),
        ),
        migrations.AlterField(
            model_name='gear',
            name='name',
            field=models.CharField(db_comment='Name of the gear', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='gear',
            name='slot',
            field=models.CharField(choices=[('Head', 'Head'), ('Body', 'Body'), ('Legs', 'Legs'), ('Hands', 'Hands'), ('Feet', 'Feet'), ('Earring', 'Earring'), ('Necklace', 'Necklace'), ('Bracelet', 'Bracelet'), ('Ring', 'Ring'), ('Shield', 'Shield'), ('Weapon', 'Weapon')], db_comment='Slot for the gear', max_length=50),
        ),
        migrations.AlterField(
            model_name='gearset',
            name='uuid',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='name',
            field=models.CharField(db_comment='Name of the job', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='race',
            name='name',
            field=models.CharField(db_comment='Race name', max_length=20, unique=True),
        ),
    ]
