# Generated by Django 4.2.6 on 2023-11-28 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_cost_name_alter_gear_acquisition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gear',
            name='ff14_db_icon',
            field=models.URLField(blank=True, null=True),
        ),
    ]
