# Generated by Django 4.2.6 on 2023-11-30 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_gear_ff14_db_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cost',
            old_name='name',
            new_name='cost_name',
        ),
        migrations.RenameField(
            model_name='gear',
            old_name='name',
            new_name='gear_name',
        ),
        migrations.RenameField(
            model_name='gearset',
            old_name='name',
            new_name='gearset_name',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='name',
            new_name='job_name',
        ),
        migrations.RenameField(
            model_name='race',
            old_name='name',
            new_name='race_name',
        ),
    ]
