# Generated by Django 4.2.6 on 2023-11-30 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_name_cost_cost_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gear',
            name='dps',
        ),
    ]
