# Generated by Django 4.2.6 on 2023-11-30 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_gear_dps'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gear',
            name='job',
        ),
        migrations.AddField(
            model_name='gear',
            name='jobs',
            field=models.ManyToManyField(related_name='gears', to='api.job'),
        ),
    ]
