# Generated by Django 4.2.6 on 2023-11-30 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_gear_job_gear_jobs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gear',
            old_name='jobs',
            new_name='job',
        ),
    ]
