# Generated by Django 4.2.6 on 2023-11-30 20:44

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rename_jobs_gear_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='gear',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, default='gear_name2', editable=True, populate_from='gear_name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gearset',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, default='gear_name', editable=True, populate_from='gearset_name'),
            preserve_default=False,
        ),
    ]
