# Generated by Django 4.2.6 on 2023-11-30 20:56

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_gear_slug_alter_gearset_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gear',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, blank=True, editable=True, null=True, populate_from='gear_name'),
        ),
        migrations.AlterField(
            model_name='gearset',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, blank=True, editable=True, null=True, populate_from='gearset_name'),
        ),
    ]
