# Generated by Django 4.2.6 on 2023-11-30 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_gear_slug_alter_gearset_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gear',
            name='ff14_db_icon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
