# Generated by Django 4.2.6 on 2023-12-02 14:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_gear_ff14_db_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='gearset',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gearset',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
