# Generated by Django 4.2.6 on 2023-12-06 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_gearset_date_added_gearset_last_modified'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gear',
            options={'ordering': ['category', 'slot', 'item_level']},
        ),
    ]
