# Generated by Django 4.2.6 on 2023-12-06 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_gear_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gear',
            options={'ordering': ['category', 'slot', '-item_level']},
        ),
    ]
