# Generated by Django 4.2.6 on 2023-12-11 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_gear_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gear',
            name='ff14_db_icon',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='gear',
            name='ff14_db_index',
            field=models.CharField(max_length=20),
        ),
    ]
